### ISSUE TITLE
QGIS Server not working with new QGIS LTR

### ISSUE THREAD

**Issue by Pedroigorggomes** [NaturalGIS/qgis_server_and_lizmap_on_windows#10]
O QGIS Server está dando erro interno:
![image](https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows/assets/168484775/660a86c5-eb40-40e5-8c39-a2d3006cf87d)

Estou com o 3.34.6-Prizren
Quando instalei a versão sem ser ltr (3.22 e 3.16) consegui fazer com que o Qgis server funcionasse, porem dentro do apache do OSGeo4W, fiz várias instalações limpas depois, com ltr e sem. No caso consegui rodar o server sempre dentro do OSGeo4W, mas não o webserver. Em todas as tentativas o server deu erro interno, já mudei o httpd.conf e tentei jogar ele para apontar para o qgis_mapserv.fcgi do OSGeo4W, mas sem sucesso. Estou numa incógnita, quando consigo ativar o QGIS Server, via OSGeo4W, não consigo o lizmap e quando consigo o lizmap não consigo o server.
[qgis_server.log](https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows/files/15160851/qgis_server.log)
[lizmap-error.log](https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows/files/15160862/lizmap-error.log)
[error.log](https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows/files/15160869/error.log)

**Comment by gioman** [comment]
Yes, seems some kind of change in the new QGIS LTR broke our recipe.

![image](https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows/assets/1951107/1ae1a4cf-6973-4311-9455-b513ab6d900f)


Will need some investigation, which we don't have time to do right now.

**Comment by gioman** [comment]
@Pedroigorggomes in phpp82.conf

change line 12 to

`FcgidInitialEnv PYTHONHOME "C:\OSGeo4W\apps\Python312"`

You must use QGIS-LTR (3.34).

**Comment by Pedroigorggomes** [comment]
It worked, thank you so much... I had been trying for 3 days already and couldn't figure out what the error was.

**Comment by gioman** [comment]
de nada!
