### ISSUE TITLE
How to access the datasets in QGIS

### ISSUE THREAD

**Issue by pjduplooy2022** [NaturalGIS/qgis_server_and_lizmap_on_windows#8]
Hi

I would like to inquire of what url I must use to access the datasets in QGIS (WMS/WFS)?

Regards

Pieter

**Comment by gioman** [comment]
@pjduplooy2022 the URL of the services will be like

`http://localhost/qgis/qgis_mapserv.fcgi.exe?map=c:/path/to/project.qgs`

where "project.qgs" is a QGIS project file in QGS format, where you have added the layers you want to publish and have configured the project accordingly in 

project > properties > QGIS Server

**Comment by pjduplooy2022** [comment]
Hi sorry
 
I mean I would like to see the datasets in QGIS, for instance for the WMS connection, you have to put in an URL.  With another Windows install of LIzmap I could use http://localhost/index.php/lizmap/service/?repository=xxx&project=xxx.

What would the first part of that URL be in your deployment?

Pieter

**Comment by gioman** [comment]
> What would the first part of that URL be in your deployment?

http://localhost/lizmap36/lizmap/www/index.php/lizmap/service?repository=***&project=***

**Comment by pjduplooy2022** [comment]
Thank you so much!!

**Comment by Gustry** [comment]
The URL is written when you click "i" button on Lizmap, you have a link.


Side note, but still important : 

> http://localhost/qgis/qgis_mapserv.fcgi

It mustn't be accessible from a public network if you have a Lizmap installed, as you will be able to bypass all securities, ACL etc provided by Lizmap.

If you a have Lizmap installed, always use URL provided by Lizmap.

**Comment by pjduplooy2022** [comment]
This Lizmap is a local install, I am learning the essentials of mapserving to see how the serving of maps work

**Comment by pjduplooy2022** [comment]
Another couple of questions.

Will the pgrouting and mapbuilder modules work?

What files need to be changed to run on a different port like 82?

If I want PostGIS support, can I change the profiles.ini.php without any problems?

**Comment by gioman** [comment]
> Will the pgrouting and mapbuilder modules work?

they are not installed.


> What files need to be changed to run on a different port like 82?

look at apache config files in

`C:\webserver\Apache24\conf`


> If I want PostGIS support, can I change the profiles.ini.php without any problems?

You don't have to change anything to have postgis support.
